# Generated by Django 4.1.3 on 2022-11-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_header_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='description',
        ),
    ]
